### ISSUE TITLE
Suggestion is not Displaying 

### ISSUE THREAD

**Issue by younas-bangash** [lapism/SearchBar-SearchView#312]
I am using the below code in order to get the result from the API and during log i successfully see the response with no erro but suggestion is not displaying 

  ```
  private void initializeSearch() {

        final SearchView mSearchView = appBarMainScreenBinding.searchView;
        if (mSearchView != null) {
            mSearchView.setVersionMargins(SearchView.VersionMargins.TOOLBAR_SMALL);
            mSearchView.setHint("search");
            mSearchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String query) {
                    mHistoryDatabase.addItem(new SearchItem(query));
                    mSearchView.close(false);
                    return true;
                }

                @Override
                public boolean onQueryTextChange(String newText) {
                    appBarMainScreenBinding.searchView.showProgress();
                    getMoviesList(newText);
                    return false;
                }
            });
            mSearchView.setOnOpenCloseListener(new SearchView.OnOpenCloseListener() {
                @Override
                public boolean onOpen() {
                    return true;
                }

                @Override
                public boolean onClose() {
                    return true;
                }
            });
        }

    }


  private void getMoviesList(final String query) {
        qeryResult.clear();
        RetrofitBuilder retrofit = new RetrofitBuilder();
        final RetrofitInterface service = retrofit.mApi;

        service.searchMovie(API_KEY,query)
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<Movies>() {
                    @Override
                    public void onCompleted() {
                        appBarMainScreenBinding.searchView.hideProgress();
                        searchAdapter.notifyDataSetChanged();
                        appBarMainScreenBinding.searchView.showSuggestions();
                    }

                    @Override
                    public void onError(Throwable e) {
                        appBarMainScreenBinding.searchView.hideProgress();
                        e.printStackTrace();
                    }

                    @Override
                    public void onNext(Movies movies) {
                        for (MovieDetails details : movies.results) {
                            Logger.d("add");
                            SearchItem searchItem = new SearchItem(details.original_title);
                            qeryResult.add(searchItem);
                        }
                    }
                });
    }
```

**Comment by HusseinElFeky** [comment]
What version do you use? This was fixed in alpha5.

**Comment by HusseinElFeky** [comment]
What version do you use?

**Comment by younas-bangash** [comment]
I solve that issue by setting setSuggestionsList() funtion Thanks @HusseinElFeky

**Comment by HusseinElFeky** [comment]
Oh yeah. I didn't notice that. Great.

**Comment by younas-bangash** [comment]
If we have and ID with SearchItem than how to handle ID ?

**Comment by HusseinElFeky** [comment]
What do you exactly mean by ID in your case here? What do you want to achieve?

**Comment by HusseinElFeky** [comment]
You can use `setOnSearchItemClickListener()` on `SearchAdapter` if you want to do actions from that `SearchItem`. Is that what you meant?

**Comment by younas-bangash** [comment]
Ohh Thanks I can solve my issue using that thanks for your help @HusseinElFeky

**Comment by HusseinElFeky** [comment]
You're welcome. ;)

**Comment by younas-bangash** [comment]
But I am now facing attempt to `java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase:` and I think which was fixed in previous version

**Comment by HusseinElFeky** [comment]
Yes, it's still an issue that needs to be fixed. Check issue #178.

**Comment by HusseinElFeky** [comment]
@lapism You should mark this as a duplicate of #178.

**Comment by Dahnark** [comment]
Some LG users is getting this crash related with SQLite:
```
Fatal Exception: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
       at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:982)
       at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:600)
       at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:349)
       at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:1032)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:972)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
       at com.lapism.searchview.SearchHistoryTable.getAllItems(SearchHistoryTable.java:111)
       at com.lapism.searchview.SearchAdapter$1.publishResults(SearchAdapter.java:182)
       at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5527)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```
It is related?

**Comment by HusseinElFeky** [comment]
Yes, I think. Same idea.

**Comment by lapism** [comment]
Guys I am gonna check it today after work.

**Comment by HusseinElFeky** [comment]
@lapism OK, cool. Can you also check #310 when you are free?

**Comment by Dahnark** [comment]
@lapism really only two users get this problem. I think is more priority the issue of duplicate ID.

![image](https://user-images.githubusercontent.com/7463564/30543941-1f9dbe42-9c85-11e7-8ad8-9a7187728e33.png)

First is duplicated ID, second onTextChanged

**Comment by HusseinElFeky** [comment]
Yeah, indeed.
